# Generated by Django 3.0.4 on 2020-08-15 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logoUrl', models.ImageField(default='default.jpg', upload_to='team')),
                ('clubState', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played', models.IntegerField(default=0)),
                ('won', models.IntegerField(default=0)),
                ('lost', models.IntegerField(default=0)),
                ('tied', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cricket.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('imageUrl', models.ImageField(default='default.jpg', upload_to='player')),
                ('jerseyNumber', models.IntegerField()),
                ('country', models.CharField(choices=[('India', 'India'), ('Australia', 'Australia'), ('West Indies', 'West Indies'), ('South Africa', 'South Africa'), ('New Zealand', 'New Zealand'), ('Sri Lanka', 'Sri Lanka'), ('Afghanistan', 'Afghanistan'), ('Pakistan', 'Pakistan'), ('England', 'England')], default='India', max_length=50)),
                ('role', models.CharField(choices=[('Batsman', 'Batsman'), ('Wicket Keeper', 'Wicket Keeper'), ('All Rounder', 'All Rounder'), ('Bowler', 'Bowler')], default='Batsman', max_length=50)),
                ('matches', models.IntegerField()),
                ('runs', models.IntegerField()),
                ('wickets', models.IntegerField()),
                ('highestScore', models.IntegerField()),
                ('fifties', models.IntegerField()),
                ('hundreds', models.IntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricket.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1Score', models.IntegerField()),
                ('team1Wicket', models.IntegerField()),
                ('team1overs', models.DecimalField(decimal_places=1, max_digits=3)),
                ('team2Score', models.IntegerField()),
                ('team2Wicket', models.IntegerField()),
                ('team2overs', models.DecimalField(decimal_places=1, max_digits=3)),
                ('result', models.CharField(blank=True, max_length=50, null=True)),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='cricket.Team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='cricket.Team')),
            ],
        ),
    ]
