# Generated by Django 3.0.4 on 2020-08-16 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='result',
            field=models.CharField(choices=[(models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mteam1', to='cricket.Team'), models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mteam1', to='cricket.Team')), (models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mteam2', to='cricket.Team'), models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mteam2', to='cricket.Team')), ('Tie', 'Tie')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mteam1', to='cricket.Team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team1Score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='team1Wicket',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='team1overs',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='match',
            name='team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mteam2', to='cricket.Team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team2Score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='team2Wicket',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='team2overs',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
