# Generated by Django 3.0.4 on 2020-08-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0002_auto_20200816_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='result',
            field=models.CharField(choices=[('Team1', 'Team1'), ('Team2', 'Team2'), ('Tie', 'Tie')], max_length=50, null=True),
        ),
    ]
