# Generated by Django 3.0.4 on 2020-08-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0003_auto_20200816_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='team1Score',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team1Wicket',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team1overs',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team2Score',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team2Wicket',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team2overs',
        ),
        migrations.AlterField(
            model_name='player',
            name='imageUrl',
            field=models.ImageField(default='default.png', upload_to='player'),
        ),
    ]
